# Generated by Django 5.2.15 on 2026-06-07 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_analysisreport_user_resume_extension_resume_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisreport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='ai_result',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='resumes.resume'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file_type',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
