# Generated by Django 5.2.15 on 2026-06-11 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('job_url', models.URLField(blank=True, max_length=1200)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('jsearch', 'JSearch'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('company', 'Company Website'), ('referral', 'Referral'), ('other', 'Other')], default='manual', max_length=30)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='saved', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('employment_type', models.CharField(blank=True, max_length=120)),
                ('salary', models.CharField(blank=True, max_length=255)),
                ('job_description_snapshot', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('date_saved', models.DateField(blank=True, null=True)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to='resumes.analysisreport')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to='resumes.resume')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='resumes_job_owner_i_47e486_idx'), models.Index(fields=['owner', 'created_at'], name='resumes_job_owner_i_c5ff43_idx'), models.Index(fields=['owner', 'next_follow_up_date'], name='resumes_job_owner_i_46d423_idx')],
            },
        ),
    ]
